### ISSUE TITLE
error install 

### ISSUE THREAD

**Issue by gege1010** [LEGENDSTER/timenode#1]
i have a error for a wallet 

Moving wallet -daemon & -client to local user directory
Archive:  daemon.zip
  inflating: timeismoney-cli
  inflating: timeismoneyd
  inflating: timeismoney-tx
install.sh: line 76: cd: .timeismoney/mainnet: No such file or directory
Configuring Wallet
install.sh: line 83: /root/.timeismoney/mainnet/timeismoney.conf: No such file or directory
install.sh: line 84: /root/.timeismoney/mainnet/timeismoney.conf: No such file or directory
install.sh: line 85: /root/.timeismoney/mainnet/timeismoney.conf: No such file or directory
install.sh: line 86: /root/.timeismoney/mainnet/timeismoney.conf: No such file or directory
install.sh: line 87: /root/.timeismoney/mainnet/timeismoney.conf: No such file or directory
install.sh: line 88: /root/.timeismoney/mainnet/timeismoney.conf: No such file or directory
install.sh: line 89: /root/.timeismoney/mainnet/timeismoney.conf: No such file or directory
install.sh: line 90: /root/.timeismoney/mainnet/timeismoney.conf: No such file or directory
install.sh: line 91: /root/.timeismoney/mainnet/timeismoney.conf: No such file or directory
install.sh: line 92: /root/.timeismoney/mainnet/timeismoney.conf: No such file or directory
install.sh: line 93: /root/.timeismoney/mainnet/timeismoney.conf: No such file or directory
install.sh: line 94: /root/.timeismoney/mainnet/timeismoney.conf: No such file or directory
install.sh: line 95: /root/.timeismoney/mainnet/timeismoney.conf: No such file or directory
Stopping Client
error: You must set rpcpassword=<password> in the configuration file:
/root/.timeismoney/mainnet/timeismoney.conf
If the file does not exist, create it with owner-readable-only file permissions.
RESTARTING DAEMON
TimeIsMoney server starting
Error: To use timeismoneyd, or the -server option to timeismoney-qt, you must set an rpcpassword in the configuration file:
/root/.timeismoney/mainnet/timeismoney.conf
It is recommended you use the following random password:
rpcuser=timeismoneyrpc
rpcpassword=J1fo3aU1pjgkhinTo5oUhv4RDpupuBNsQkmEserWzS2G
(you do not need to remember this password)
The username and password MUST NOT be the same.
If the file does not exist, create it with owner-readable-only file permissions.
It is also recommended to set alertnotify so you are notified of problems;
for example: alertnotify=echo %s | mail -s "TimeIsMoney Alert" admin@foo.com

error: You must set rpcpassword=<password> in the configuration file:
/root/.timeismoney/mainnet/timeismoney.conf
If the file does not exist, create it with owner-readable-only file permissions.
error: You must set rpcpassword=<password> in the configuration file:
/root/.timeismoney/mainnet/timeismoney.conf
If the file does not exist, create it with owner-readable-only file permissions.
error: You must set rpcpassword=<password> in the configuration file:
/root/.timeismoney/mainnet/timeismoney.conf
If the file does not exist, create it with owner-readable-only file permissions.
Waiting for Node to sync{NC}
error: You must set rpcpassword=<password> in the configuration file:
/root/.timeismoney/mainnet/timeismoney.conf
If the file does not exist, create it with owner-readable-only file permissions.

Thank you for installing the TimeIsMoney HOT/COLD wallet.  Follow the instructions to move to the NEXT step.

**Comment by LEGENDSTER** [comment]
Just hit cd and go to root directory and then hit `cd .timeismoney/mainnet` manually. It should work. Most probably you ran the script without su permission.
